### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to WorldGuardExtraFlags v4.1.4-DEV

### ISSUE THREAD

**Issue by andrewkm** [isokissa3/WorldGuardExtraFlagsPlugin#114]
Got the following during a /wg reload
https://pastebin.com/raw/yFBU8TUR

WorldGuard: 7.0.3-2030
Paper: 1.15.2-176

**Comment by isokissa3** [comment]
WorldGuard seems to remove the world configs for short period of time before applying the new config. Because the chat is async, meaning that it runs on off the game thread there is small window where the plugin is unable to find the world settings.

This is so rare case that I won't even bother to do anything with this
