### ISSUE TITLE
not issue but question / disable end portals

### ISSUE THREAD

**Issue by ProSharkyt** [isokissa3/WorldGuardExtraFlagsPlugin#116]
can't find an option to disable end portals, or does disable nether portal will disable the end  portals too?

**Comment by isokissa3** [comment]
No, theres no option to disable end portals. I don't see point for one as they are server controlled so you already have way to disable them by other means.

**Comment by Pemigrade** [comment]
How would you disable an end portal in just one world? I'm unable to find a way to do it since Multiverse Nether Portals doesn't support 1.15.

I'd like to see this feature added to worldguardextraflags if there's currently no way to do it, and I can make a Feature Request if that helps keep things organized.
