### ISSUE TITLE
Entry flags not always working

### ISSUE THREAD

**Issue by Pugabyte** [isokissa3/WorldGuardExtraFlagsPlugin#19]
Latest 1.12.2, WGEF 2.14.3

I have a few regions that use the console-command-on-entry and command-on-entry flags, and sometimes, it simply doesn't work. Relogging doesn't fix it. I'm sure that they are not overriding the region

EDIT: duplicate of Duplicate of #15 #13 ....

**Comment by isokissa3** [comment]
Is this still issue?

**Comment by Pugabyte** [comment]
Last I checked this was still an issue, about a month ago. It's hard to reproduce. 

I have a command on my server for staff members to turn WorldGuard bypass on and off. This works okay, aside from the fact that when turning it off, you have to change worlds or relog; but sometimes, randomly, normal players with no bypass permissions whatsoever were able to go into a region with a command-on-entry flag without being teleported.

**Comment by isokissa3** [comment]
On 3.0.0 I have changed that I no longer use WorldGuards bypass check and instead check for permissions, all changes should reflect instantly.

Have you tried using teleport-on-entry? Tho that won’t work when you want to teleport across worlds because of WG limit, tho that could be changes with few edits.

Do you have any regions inside the other region? That should not effect it but who knows? Also could be WG bug?

**Comment by Pugabyte** [comment]
A lot of the commands that are being run via the flag arent static teleports (e.g. `/checkpoint tp`) so we're always just been using command flags. 

I want to say I remember doing some debug on this and finding it was still triggering a RegionEnterEvent when the command wouldn't work, but its been so long that I can't say for sure. Today or tomorrow I will update and try to reproduce the issue and get back to you.

**Comment by Pugabyte** [comment]
Apologize for the delay. It appears to be working well now. Thank you!
